doctrine:
    dbal:
        driver: pdo_sqlite
        path: '%kernel.project_dir%/var/data/sqlite.db3'
        charset: UTF8
    orm:
        mappings:
            App:
                type: attribute
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
