imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    #translator:      { fallback: "%locale%" }
    secret:          "notsosecret"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    default_locale:  "en"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

jms_di_extra:
    locations:
        all_bundles: false
        bundles: [SDTetrisBundle]
        directories: ["%kernel.root_dir%/../src"]

services:
    keyboard_helper:
        class: SD\ConsoleHelper\Keyboard
    screen_buffer:
        class: SD\ConsoleHelper\ScreenBuffer

parameters:
    horizontal_scale: 2

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "pdo_sqlite"
        host:     "localhost"
        port: ~
        dbname:   "leader_board"
        user:     "root"
        password: ~
        charset:  UTF8
        path: "%kernel.root_dir%/data/sqlite.db3"
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
          default:
            connection: default
            mappings:
              SDTetrisBundle: ~
