parameters:
    board_width: 10
    board_height: 20
    horizontal_scale: 2

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        bind:
            $boardWidth: '%board_width%'
            $boardHeight: '%board_height%'
            $width: '%board_width%'
            $height: '%board_height%'
            $horizontalScale: '%horizontal_scale%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/Event/'
            - '../src/Kernel.php'

    SD\ConsoleHelper\Keyboard: ~
    SD\ConsoleHelper\ScreenBuffer: ~

    App\Repository\GameScoreRepository:
        factory: ['@doctrine.orm.entity_manager', getRepository]
        arguments:
            - App\Entity\GameScore
